{
 "title": "Flask server",
 "time": { "from": "2023-01-12T05:51:10.824Z", "to": "2023-01-12T05:51:37.107Z" },
 "panels": [
  {
   "title": "Количество успешных запросов в секунду",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_request_latency_seconds_count{endpoint=\"/test\",method=\"GET\"}[30s])",
     "legendFormat": "endpoint={{endpoint}}"
    },
    {
     "expr": "rate(app_request_latency_seconds_count{endpoint=\"/favicon.ico\",method=\"GET\"}[30s])",
     "legendFormat": "endpoint={{endpoint}}"
    }
   ]
  },
  {
   "title": "Количество неудачных ответов в секунду",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    app_request_latency_seconds_count{status!=\"200\"}[30s]\n  )\n)"
    }
   ]
  },
  {
   "title": "Потребление памяти",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job='flask-server'}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU потребление",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(\n  process_cpu_seconds_total{job=\"flask-server\"}[30s]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}